// <auto-generated />
using System;
using EmpadronamientoBackend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313063342_se agregan tablas de sistema")]
    partial class seagregantablasdesistema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Catalogos.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("Clave", "OrganizacionId")
                        .IsUnique();

                    b.ToTable("Catalogos", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Catalogos.CatalogoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("CatalogoId", "Orden");

                    b.ToTable("CatalogoItems", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.ConfiguracionGlobal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaxIntentosLoginFallidos")
                        .HasColumnType("int");

                    b.Property<int>("MinutosBloqueo")
                        .HasColumnType("int");

                    b.Property<bool>("ModoAdminGlobalActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizacionMaestraId")
                        .HasColumnType("int");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionGlobal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1",
                            MaxIntentosLoginFallidos = 5,
                            MinutosBloqueo = 15,
                            ModoAdminGlobalActivo = true,
                            NombreSistema = "BenitezLabs Enterprise",
                            OrganizacionMaestraId = 1,
                            ZonaHoraria = "Central Standard Time"
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.DireccionPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Colonia")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroInterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("DireccionesPersona", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.EmpadronamientoPersona", b =>
                {
                    b.Property<int>("EmpadronamientoId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("EmpadronamientoId", "PersonaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("EmpadronamientoPersonas", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Empadronamientos.Empadronamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CRPId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CRPNombre")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Folio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LugarEmpadronamientoId")
                        .HasColumnType("int");

                    b.Property<string>("NarrativaHechos")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LugarEmpadronamientoId");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("UsuarioResponsableId");

                    b.ToTable("Empadronamientos", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Empadronamientos.LugarEmpadronamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Colonia")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroInterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("LugaresEmpadronamiento", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Familiar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentescoId")
                        .HasColumnType("int");

                    b.Property<string>("ParentescoNombre")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Familiares", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.FotoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoFotoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoFotoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("FotosPersona", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("K")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("K")
                        .IsUnique();

                    b.ToTable("Modulos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            K = "u",
                            Nombre = "Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            K = "r",
                            Nombre = "Roles"
                        },
                        new
                        {
                            Id = 3,
                            K = "o",
                            Nombre = "Organizaciones"
                        },
                        new
                        {
                            Id = 4,
                            K = "c",
                            Nombre = "Configuración"
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Colonia")
                        .HasColumnType("longtext");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoSuspension")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroInterior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmailContacto")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("Organizaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CP = 0,
                            Calle = "",
                            CreadoPor = "System_Seed",
                            Descripcion = "Organización Maestra del Sistema",
                            DispositivoCreacion = "Console_Setup",
                            EmailContacto = "admin@benitezlabs.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaVencimiento = new DateTime(2076, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1",
                            Nombre = "BenitezLabs Admin",
                            NumeroExterior = "",
                            NumeroInterior = "",
                            PlanId = 1
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.OrganizacionModulo", b =>
                {
                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrganizacionId", "ModuloId");

                    b.HasIndex("ModuloId");

                    b.ToTable("OrganizacionModulos", (string)null);

                    b.HasData(
                        new
                        {
                            OrganizacionId = 1,
                            ModuloId = 1,
                            Activo = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaActivacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1"
                        },
                        new
                        {
                            OrganizacionId = 1,
                            ModuloId = 2,
                            Activo = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaActivacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1"
                        },
                        new
                        {
                            OrganizacionId = 1,
                            ModuloId = 3,
                            Activo = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaActivacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1"
                        },
                        new
                        {
                            OrganizacionId = 1,
                            ModuloId = 4,
                            Activo = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaActivacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1"
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Apodo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("EscolaridadId")
                        .HasColumnType("int");

                    b.Property<string>("EscolaridadNombre")
                        .HasColumnType("longtext");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivilNombre")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Estatura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("longtext");

                    b.Property<string>("OficioProfesion")
                        .HasColumnType("longtext");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Originario")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RedSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRedSocialId")
                        .HasColumnType("int");

                    b.Property<string>("TipoRedSocialNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UrlPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("RedesSociales", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("Nombre", "OrganizacionId")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1",
                            Nombre = "SuperAdmin",
                            OrganizacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpCreacion = "127.0.0.1",
                            Nombre = "Usuario",
                            OrganizacionId = 1
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RolePermiso", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("Lvl")
                        .HasColumnType("int")
                        .HasComment("Nivel de acceso: 1-Leer, 2-Escribir, 3-Borrar");

                    b.HasKey("RoleId", "ModuloId");

                    b.HasIndex("ModuloId");

                    b.ToTable("RolesPermisos", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 2,
                            ModuloId = 1,
                            Lvl = 1
                        },
                        new
                        {
                            RoleId = 2,
                            ModuloId = 2,
                            Lvl = 1
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RostroPersona", b =>
                {
                    b.Property<int>("IdRostro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRostro"));

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("BoundingBoxHeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BoundingBoxLeft")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BoundingBoxTop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BoundingBoxWidth")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Confianza")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FaceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("IdRostro");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("RostrosPersona", (string)null);
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("CorreoConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DispositivoCreacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DispositivoUltimaActualizacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imagen")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpUltimaActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacionCorreo")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "BenitezLabs",
                            Correo = "admin@benitezlabs.com",
                            CorreoConfirmado = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosFallidos = 0,
                            IpCreacion = "127.0.0.1",
                            Nombre = "Admin",
                            OrganizacionId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEKIjY3wt3qPaRhFO0BGcEIuIfNdUuqgxjWYU/viWo0ZQgAPDOvPQS2wx2XedAp2pdg==",
                            RoleId = 1,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Operator",
                            Correo = "user@benitezlabs.com",
                            CorreoConfirmado = true,
                            CreadoPor = "System_Seed",
                            DispositivoCreacion = "Console_Setup",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosFallidos = 0,
                            IpCreacion = "127.0.0.1",
                            Nombre = "Demo",
                            OrganizacionId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEEYSCDySFgvE0UwM0+n79baMDGhN6nAIaFNUOilvMDF87VPHDXj3iba8KytIQC9ToQ==",
                            RoleId = 2,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.UsuarioSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UltimaActividad")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioSesiones", (string)null);
                });

            modelBuilder.Entity("Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxUsuarios = 9999,
                            Nombre = "Plan Maestro / Enterprise",
                            Precio = 0m
                        });
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Catalogos.Catalogo", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Catalogos.CatalogoItem", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Catalogos.Catalogo", "Catalogo")
                        .WithMany("Items")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.DireccionPersona", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.EmpadronamientoPersona", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Empadronamientos.Empadronamiento", "Empadronamiento")
                        .WithMany("Personas")
                        .HasForeignKey("EmpadronamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("Empadronamientos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empadronamiento");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Empadronamientos.Empadronamiento", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Empadronamientos.LugarEmpadronamiento", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarEmpadronamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lugar");

                    b.Navigation("Organizacion");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Empadronamientos.LugarEmpadronamiento", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Familiar", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("Familiares")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.FotoPersona", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("Fotos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Organizacion", b =>
                {
                    b.HasOne("Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.OrganizacionModulo", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Modulo", "Modulo")
                        .WithMany("OrganizacionesConAcceso")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("ModulosContratados")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Persona", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RedSocial", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("RedesSociales")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Role", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RolePermiso", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Modulo", "Modulo")
                        .WithMany("RolePermisos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Role", "Role")
                        .WithMany("Permisos")
                        .HasForeignKey("RoleId");

                    b.Navigation("Modulo");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.RostroPersona", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany()
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Persona", "Persona")
                        .WithMany("Rostros")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenitezLabs.Domain.Entities.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.UsuarioSesion", b =>
                {
                    b.HasOne("BenitezLabs.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Catalogos.Catalogo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Empadronamientos.Empadronamiento", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("OrganizacionesConAcceso");

                    b.Navigation("RolePermisos");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Organizacion", b =>
                {
                    b.Navigation("ModulosContratados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Empadronamientos");

                    b.Navigation("Familiares");

                    b.Navigation("Fotos");

                    b.Navigation("RedesSociales");

                    b.Navigation("Rostros");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BenitezLabs.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
